{% set name = "moonrepo-moon" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moonrepo/moon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fabfda01694bba2730f9a658b668a0d6e4fd7067086916728a445bf80fa7ed86

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - make                             # [linux]

test:
  commands:
    - moon --help

about:
  home: https://moonrepo.dev/
  summary: 'Build system for managing codebases'
  description: |
    A task runner and monorepo management tool for the web ecosystem, written in Rust.
    Supports JavaScript, TypeScript, Rust, Go, Ruby, and more <https://moonrepo.dev/docs#supported-languages>
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://moonrepo.dev/docs
  dev_url: https://github.com/moonrepo/moon

extra:
  recipe-maintainers:
    - corker
