{% set name = "moonrepo-moon" %}
{% set version = "1.30.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moonrepo/moon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 66dd51daeccf0e27c7aeb251c1788e516fc0a8b7b8a3514797f0c8ca6226b68f

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - vs2019_win-64                    # [win]
    - cargo-bundle-licenses
    - make

test:
  commands:
    - moon --help

about:
  home: https://moonrepo.dev/
  summary: 'Build system for managing codebases'
  description: |
    A task runner and monorepo management tool for the web ecosystem, written in Rust.
    Supports JavaScript, TypeScript, Rust, Go, Ruby, and more <https://moonrepo.dev/docs#supported-languages>
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://moonrepo.dev/docs
  dev_url: https://github.com/moonrepo/moon

extra:
  recipe-maintainers:
    - corker
