{% set name = "moonrepo-moon" %}
{% set version = "1.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moonrepo/moon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9206dfb2299d2f49b898bd48fe5444529a5afc14ec19ebea7d2ebf766fa687dc

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - make                             # [linux]

test:
  commands:
    - moon --help

about:
  home: https://moonrepo.dev/
  summary: 'Build system for managing codebases'
  description: |
    A task runner and monorepo management tool for the web ecosystem, written in Rust.
    Supports JavaScript, TypeScript, Rust, Go, Ruby, and more <https://moonrepo.dev/docs#supported-languages>
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://moonrepo.dev/docs
  dev_url: https://github.com/moonrepo/moon

extra:
  recipe-maintainers:
    - corker
